# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ac5cb03c680bd83e47a93744155026a084cc4e7404f98c5a25b17cde32dd87fbf40e9784870bc8a790b2e3f189266c08cea39a127046444e060393240b4418d

test:
  secret_key_base: 15e11f591f14760e16bcdc837268f8069d700491c9dc9c2bad4070dc7064305c448439c4f525cf3617d4642bf81c57c20c9be1124f662678d9eca02fc364b9b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
